checkout: dinaldoap/issue25
commit: 56cb74e3de254ddd1ccaee8b34bc3e94b445e3a9
context:
  email: dinaldoap@gmail.com
  full_name: Dinaldo A. Pessoa
  github_username: dinaldoap
  project_name: Cookiecutter Python VSCode GitHub
  project_short_description:
    Cookiecutter Python VSCode GitHub provides a Python Package
    template with an IDE (Visual Studio Code) and a CI/CD (GitHub Actions) already
    setup.
  project_slug: cookiecutter-python-vscode-github
  project_slug_underscore: cookiecutter_python_vscode_github
directory: cookiecutter
merge_strategies:
  "*.json": comprehensive
  "*.toml": comprehensive
  "*.yaml": comprehensive
  "*.yml": comprehensive
no_input: false
overwrite:
  - "*"
overwrite_exclude:
  - "*.py"
password: null
skip_generation: []
skip_hooks: false
skip_if_file_exists: false
template: https://github.com/dinaldoap/cookiecutter-python-vscode-github
